In [7]:
import torch
import numpy as np
from value_network import ValueNet
from residual_network import ResidualNet

In [8]:
v = torch.load("../networks/value.pth")
r = torch.load("../networks/residual.pth")

In [9]:
a = torch.rand((10, 3))

In [10]:
v(a)

tensor([[ 4.4492],
        [ 4.4418],
        [ 0.8669],
        [13.8824],
        [ 6.6933],
        [ 7.5582],
        [ 9.6710],
        [ 3.6279],
        [ 8.0366],
        [ 9.9008]], grad_fn=<AddmmBackward>)

In [11]:
r(a)

tensor([[ 4.5405],
        [ 4.7892],
        [ 0.2938],
        [13.9717],
        [ 7.2821],
        [ 8.1127],
        [10.2257],
        [ 3.6861],
        [ 8.2241],
        [10.4557]], grad_fn=<MulBackward0>)

In [13]:
v.batch_hessian(a)

tensor([[[ 14.4079,  -5.9015,   6.2042],
         [ -5.9015,  22.0087,  -5.3604],
         [  6.2042,  -5.3604,  16.6606]],

        [[ 14.2956,  -3.0941,   2.0775],
         [ -3.0941,  28.5466, -10.5077],
         [  2.0775, -10.5077,  21.4808]],

        [[  8.1007,  -0.0364,  -1.0680],
         [ -0.0364,  18.1228,  -0.3347],
         [ -1.0680,  -0.3347,   6.7742]],

        [[ 13.1535,  -9.5092,   2.2297],
         [ -9.5092,  15.4948, -12.3978],
         [  2.2297, -12.3978,  18.5766]],

        [[ 17.3324,  -8.2756,   2.8515],
         [ -8.2756,  29.9968, -11.5963],
         [  2.8515, -11.5963,  18.3448]],

        [[ 14.1562,  -4.5469,   3.5034],
         [ -4.5469,  28.2919, -13.1454],
         [  3.5034, -13.1454,  26.4446]],

        [[ 19.9313, -10.2139,   4.1113],
         [-10.2139,  27.9903, -14.9174],
         [  4.1113, -14.9174,  19.1680]],

        [[ 13.9329,  -4.9247,   4.4496],
         [ -4.9247,  23.0752,  -5.6474],
         [  4.4496,  -5.6474,  17.4747]],



In [14]:
r.batch_approx_hessian(a)

tensor([[[ 9.0235, -7.1945,  5.0474],
         [-7.1945, 35.2500,  2.2604],
         [ 5.0474,  2.2604, 20.1921]],

        [[ 8.9444, -4.4424,  2.4633],
         [-4.4424, 30.0125, -0.1468],
         [ 2.4633, -0.1468,  2.7189]],

        [[ 9.2757, -0.5883,  3.7652],
         [-0.5883, 21.1534, -7.0685],
         [ 3.7652, -7.0685, 16.0414]],

        [[ 4.1619, -2.4517,  0.4902],
         [-2.4517, 23.5315, -4.7040],
         [ 0.4902, -4.7040,  6.8499]],

        [[ 2.4822, -2.6989, -0.5903],
         [-2.6989, 19.6447, -2.9902],
         [-0.5903, -2.9902, 14.8432]],

        [[ 9.3175, -3.4068,  2.8903],
         [-3.4068, 28.9823, -0.9348],
         [ 2.8903, -0.9348,  6.0541]],

        [[ 1.9412, -1.4174, -2.8329],
         [-1.4174, 18.0835, -3.6674],
         [-2.8329, -3.6674, 17.6002]],

        [[ 7.9196, -6.7908,  4.2251],
         [-6.7908, 28.2139, -0.3884],
         [ 4.2251, -0.3884,  9.9693]],

        [[ 9.3614, -5.6605,  8.9466],
         [-5.6605, 36.5324,  4.221

In [15]:
r.batch_hessian(a)

AttributeError: 'ResidualNet' object has no attribute 'hessian_value'